version: '3.9'
services:
  # CockroachDB Load Balancer
  crdb-lb:
    hostname: crdb-lb
    image: haproxy:latest
    volumes: ['./crdb-lb.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro']
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8181:8081"
    depends_on:
      - roach-01
      - roach-02
      - roach-03
    networks:
      - roachnet

  # CockroachDB default topology - 3 nodes
  roach-01:
    # see https://hub.docker.com/r/cockroachdb/cockroach/tags
    image: cockroachdb/cockroach:v21.1.10
    hostname: roach-01
    volumes: ["./cockroach-data/roach-01:/cockroach/cockroach-data"]
    command: start --insecure --join=roach-01 --locality=region=us-east-fl,datacenter=us-east-fl-a --cache=.25 --max-sql-memory=.25 --logtostderr=WARNING --log-file-verbosity=WARNING
    networks:
      - roachnet
  roach-02:
    # see https://hub.docker.com/r/cockroachdb/cockroach/tags
    image: cockroachdb/cockroach:v21.1.10
    hostname: roach-02
    volumes: ["./cockroach-data/roach-02:/cockroach/cockroach-data"]
    command: start --insecure --join=roach-01 --locality=region=us-east-fl,datacenter=us-east-fl-a --cache=.25 --max-sql-memory=.25 --logtostderr=WARNING --log-file-verbosity=WARNING
    depends_on:
    - roach-01
    networks:
      - roachnet
  roach-03:
    # see https://hub.docker.com/r/cockroachdb/cockroach/tags
    image: cockroachdb/cockroach:v21.1.10
    hostname: roach-03
    volumes: ["./cockroach-data/roach-03:/cockroach/cockroach-data"]
    command: start --insecure --join=roach-01 --locality=region=us-east-fl,datacenter=us-east-fl-a --cache=.25 --max-sql-memory=.25 --logtostderr=WARNING --log-file-verbosity=WARNING
    depends_on:
    - roach-01
    networks:
      - roachnet

  kafka1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka1
    hostname: kafka1
    environment:
      KAFKA_NODE_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka1:29092,CONTROLLER://kafka1:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    command: "bash -c '/tmp/run_workaround.sh && /etc/confluent/docker/run'"
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - roachnet
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:29092
      - KAFKA_CLUSTERS_0_READONLY=true
    networks:
      - roachnet
  vector:
    #image: timberio/vector:latest-debian
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Required for the docker guest(container)/host interaction
    ports:
     - "8686:8686"
    depends_on:
      - crdb-lb
    networks:
      - roachnet
networks:
  roachnet:
    driver: bridge

# https://stackoverflow.com/questions/54034183/haproxy-docker-container-is-not-able-to-load-balance-across-my-cockroach-db-dock
