import pandas as pd
import json

# Load the nodes.json file generated by the debug command:
## cockroach debug zip crdb_node.zip --certs-dir=certs --host=<node-ip>:26257
with open('nodes.json', 'r') as f:
    data = json.loads(f.read())

# Get the nodes object
df = pd.json_normalize(data["nodes"])
# print(df)
# print(df.columns.values.tolist())
# Write the nodes output to a CSV file for quick analysis
# with Pandas, SQLAlchemy can be used to send it to CRDB
df.to_csv('nodes.csv', index=False)
